<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>default</LangVersion>
    <GameDir>E:\Game\Steam\steamapps\common\Escape from Duckov\Duckov_Data\Managed</GameDir>
  </PropertyGroup>

   <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>$(DefineConstants);COMBATMAID_DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(GameDir)\*.dll" 
               Exclude="$(GameDir)\System.*;
                        $(GameDir)\mscorlib.dll;
                        $(GameDir)\netstandard.dll;
                        $(GameDir)\Microsoft.*;
                        $(GameDir)\Mono.*;
                        $(GameDir)\ExCSS.Unity.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="FastModdingLib">
      <HintPath>FastModdingLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="SkillTreeSystem.7z" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Patches\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;$(TargetPath)&quot; &quot;E:\Game\Steam\steamapps\common\Escape from Duckov\Duckov_Data\Mods\CombatMaid\CombatMaid.dll&quot;&#xA;xcopy /Y /S /I &quot;$(ProjectDir)Localization\*.csv&quot; &quot;E:\Game\Steam\steamapps\common\Escape from Duckov\Duckov_Data\Mods\CombatMaid\Localization\&quot;&#xA;xcopy /Y /E /I &quot;$(ProjectDir)Res\*&quot; &quot;E:\Game\Steam\steamapps\common\Escape from Duckov\Duckov_Data\Mods\CombatMaid\&quot;" />
  </Target>

</Project>